<footer class="site-footer">
    <p>This theme has been generated by <a href="https://github.com/troychaplin/wp-monorepo-manager">WP Monorepo Manager</a></p>
</footer>
<?php wp_footer(); ?>
</body>

</html>